print('      +                           +        ')
print('    +   +                       +   +')
print('  +       +                   +        +')
print('+           +               +             +')
print('+             +            +              +')
print(' +              +        +               +   ')
print('  +               +    +                +  ')
print('   +                +                  +')
print('    +                                 +')
print('     +         CHAOMEI JINANG        +  ')
print('      +                             +')
print('       +       $$I LOVE YOU$$      +')
print('        +                         +')
print('         +                       + ')
print('          +                     +')
print('           +                   +  ')
print('             +               +') 
print('               +           +')
print('                 +       +')
print('                   +   +')
print('                     +         ')