brands = ['BMW','BENZ','AUDI','TOYOTA','NISSAN']
#brands.sort()
#print(brands)
#brands.sort(reverse=True)
print(brands)
#print(brands)
print(sorted(brands))
print(brands)
print(sorted(brands,reverse=True))
brands.reverse()
print(brands)
print(len(brands))
print("练习--------------------------------------------")
places = ['xian','shanghai','hangzhou','beijing','sanya']
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=True))
print(places)
reverse(places)
print(places)
reverse(places)
print(places)
sort(places)
print(places) 
sort(places) 
print(places)
print(len(places))
